### PR TITLE
v2.3.6 release

### PR DESCRIPTION
**Pull request by davidjgonzalez**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@kwin  Wrt to #754 - it looks like we have to go through and add the `cloud` profile to the release github action commands to get the all-cloud artifact deployed-- does that sound right?

**Comment by kwin** [comment]
Why 2.3.6? Milestone in GH says 2.4.0 and given the change for separating cloud/classic this makes way more sense to me.

**Comment by davidjgonzalez** [comment]
I bumped build since these are effectively bug fixes - there's no new features persay in this release. 
It actually seems more like a major change, since if someone is deploying to the cloud, they have to change the classifier (the current coords won't be correct). It felt like a sad 3.0 release tho :)

Anyhow 2.4.0 is fine - the release GA failed anyhow, so have to figure that out an try again!

**Comment by davidjgonzalez** [comment]
@kwin  FYI - i released as 2.4.0 (reverted the 2.3.6) as i had to fix some stuff to get the release to go through anyhow.

**Pull request merged**
