### PR TITLE
Asset Details - PDF Viewer

### PR DESCRIPTION
**Pull request by davidjgonzalez**
## Description

Component that displays  PDF assets in the Adobe DC PDF viewer. This requires a Adobe PDF Embed API credentials to be set in the Design Dialog for the component: https://acrobatservices.adobe.com/dc-integration-creation-app-cdn/main.html?api=pdf-embed-api#

The trick with this component is currently the AssetType asset details page selector, uses the overly-broad categories (for example, a PDF and Word Doc are both considered "Documents" and uses the .../details/documents.html. details page.  Since this component wont handle Word docs (unless you make a PDF rendition of the Word doc to display) ... its hard to create a Details page that handles both types. So, as part of this PR ive added an "Content Type" computed property that is a more fine-grained version of Asset Type (so an application/pdf get a PDF value instead of Document) so you can more easily target specific content types.

2023-12-14 at 2 36 PM

## Motivation and Context

Ability to show real previews of PDF files.

## How Has This Been Tested?

Tested on AEM SDK 2013.12.

## Screenshots (if appropriate):

2023-12-14 at 12 25 PM

2023-12-14 at 12 29 PM

2023-12-14 at 12 29 PM

2023-12-14 at 12 29 PM

2023-12-14 at 12 30 PM

2023-12-14 at 12 31 PM

2023-12-14 at 2 36 PM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by Robedean** [comment]
@davidjgonzalez this looks great. Thank you for working on this. I'm assuming this is PDF only and not for PowerPoint as well?

**Comment by davidjgonzalez** [comment]
@Robedean i dont think the PDF Embed API supports PPT since its a PDF viewer. You could create PDFs renditions FROM a PPT (to be honest, i dont know how youd do this - but its theoretically possible... maybe via a Asset Compute worker?) ... and then make a details/powerpoint.html that configures this componetn to read the "ppt-pdf" rendition you generate (youd need a matching Named Rendition - but thats 1 line config in OSGi property) .. 

Do you know if the PDF Embed API is supposed to support PPTs somehow? (im not an expert w/ this plugin so you might know something i dont)

**Comment by RahulMohann** [comment]
> @Robedean i dont think the PDF Embed API supports PPT since its a PDF viewer. You could create PDFs renditions FROM a PPT (to be honest, i dont know how youd do this - but its theoretically possible... maybe via a Asset Compute worker?) ... and then make a details/powerpoint.html that configures this componetn to read the "ppt-pdf" rendition you generate (youd need a matching Named Rendition - but thats 1 line config in OSGi property) ..
> 
> Do you know if the PDF Embed API is supposed to support PPTs somehow? (im not an expert w/ this plugin so you might know something i dont)

Hi @davidjgonzalez , It works. I see there is a pdf rendition getting created for the PowerPoint presentations uploaded to AEM. Not sure if this is OOB or as a result of some custom created process. And when I select 'pdf' as the rendition to be rendered in the pdf component, it works. Thanks a lot!

**Comment by RahulMohann** [comment]
@davidjgonzalez  Just a question, I see we need to configure the client ID in the design dialog of the pdf component. Is there a way we can keep this in the code base, so that it will be configured through the deployments. Please note, we have 3 different asset share common instances - dev, stage and prod. So we use 3 different client ids for 3 instances. Can we tackle this and store it in the codebase somehow?

**Comment by davidjgonzalez** [comment]
https://github.com/adobe/asset-share-commons/pull/1069

3.8.0 will have have an OSGi configuration you can fall back to.

**Pull request merged**
