### PR TITLE
enable "cloud" profile for all CI builds and release

### PR DESCRIPTION
**Pull request by kwin**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bstopp** [comment]
If there is a `cloud` profile, is there also a non-cloud profile? Each profile needs its own build command in the workflows to ensure the artifacts are created and published

**Comment by kwin** [comment]
There is only cloud, the classic artifacts are always built (because the cloud module relies on them)

**Comment by bstopp** [comment]
If Cloud artifacts are always built; why have a separate profile for them?

**Comment by kwin** [comment]
The build is faster without profile cloud as then you only build the classic artifacts. However the profile „cloud“ is already merged to develop. For now we should make sure that CI covers it. If you have a different proposal how to build for cloud please raise it separately.

**Comment by davidjgonzalez** [comment]
@kwin IIUC you introduced the `cloud` profile, mainly for local development? (vs. just always building everything) to make that build/cycle faster for 6.5.x developers?

**Comment by kwin** [comment]
@davidjgonzalez Yes, the separation in a dedicated profile is exactly for that use case.

**Comment by kwin** [comment]
@davidjgonzalez Either this PR should be merged or the profile `cloud` should be removed. Currently the CI is just incomplete!

**Review by davidjgonzalez — APPROVED** [review]

**Pull request merged**
